image: node:8
stages:
  - test
  - version
  - build
  - deploy

.version:
#  variables:
#    CI_DEBUG_TRACE: "true"
  stage: version
  only:
    - master
  except:
    - tags
    - triggers
  script:
#    - export CI_PUSH_REPO=`echo $CI_REPOSITORY_URL | perl -pe 's#.*@(.+?(\:\d+)?)/#git@\1:#' | perl -pe 's/:gitlab\//:\//'`
    - export CI_PUSH_REPO=`echo $CI_REPOSITORY_URL | perl -pe "s#(.*)\/\/(.*)@(.*)#\1\/\/yehiyam:${HKUBE_CI_TOKEN}@\3#"`
#    - eval $(ssh-agent -s)
#    - ssh-add <(echo "$CI_KEY")
    - export TMP_BRANCH_NAME=ci_processing_$CI_JOB_ID
    - git checkout -b $TMP_BRANCH_NAME
    - git remote set-url --push origin "$CI_PUSH_REPO"
    - git config user.name "${GITLAB_USER_NAME}"
    - git config user.email "${GITLAB_USER_EMAIL}"
    - npm version patch -m "$(git log -1 --pretty=%B) .... bump version [skip ci]"
    - echo push url "$TMP_BRANCH_NAME:${CI_COMMIT_REF_NAME}"
    - git remote -v
    - git push origin $TMP_BRANCH_NAME:${CI_COMMIT_REF_NAME} --follow-tags
    - curl -X POST -F "token=${TRIGGER_TOKEN}" -F "ref=$(git describe --abbrev=0 --tags)" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/trigger/pipeline"

build:
#  image: yehiyam/docker-node:8
  image: docker:latest
  services:
    - docker:dind
  stage: build
#  only:
#    - triggers
  script:
#    - npm --registry=http://npmhkube.ddns.net:4873 install
#    - npm run build
    - echo ${HKUBE_CI_TOKEN} | docker login -u yehiyam --password-stdin registry.gitlab.com
    - PRIVATE_REGISTRY=registry.gitlab.com/greenapes/hkube/registry npm run build
#    - docker build -t registry.gitlab.com/greenapes/hkube/registry/hkube/worker -f dockerfile/Dockerfile .
.deploy:
  stage: deploy
  only:
    - triggers
  script:
    - VERSION=$(git describe --abbrev=0 --tags);VERSION=${VERSION%.*}
    - MESSAGE="Triggered by ${CI_PROJECT_NAME:-Unknown}. $(git log -1 --pretty=%B)"
    - curl -X POST -H "PRIVATE-TOKEN:MXgU_4aWxXLfzWQPHv9M" -F tag_name="${VERSION}.$(date +%s)" -F release_description="Version ${VERSION} $(date)" -F message="${MESSAGE}" -F ref=master http://gitlab.rms/gitlab/api/v3/projects/47/repository/tags

cache:
  paths:
  - node_modules/

.test:
  stage: test
  services:
    - name: redis:latest
      alias: redis
    - name: quay.io/coreos/etcd:v2.3.8
      alias: etcd
  variables:
    ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379,http://0.0.0.0:4001"
    ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379,http://etcd:4001"
  script:
   - npm --registry http://npmhkube.ddns.net:4873 install
   - export ETCD_CLIENT_SERVICE_HOST=etcd
   - export REDIS_SERVICE_HOST=redis 
   - wget -qO- http://${ETCD_CLIENT_SERVICE_HOST}:4001/version
   - NODE_ENV=test npm run test

