# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
  - name: redis:latest
    alias: redis
  - name: quay.io/coreos/etcd:v2.3.8
    alias: etcd
variables:
  ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379,http://0.0.0.0:4001"
  ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379,http://etcd:4001"
# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

test_async:
  script: 
   - npm --registry http://greenape.ddns.net/npm/ install
   - export ETCD_SERVICE_HOST=etcd
   - export REDIS_SERVICE_HOST=redis 
   - wget -qO- http://${ETCD_SERVICE_HOST}:4001/version
   - npm run test

